version: "3"

services:
  webhook:
    build:
      context: .
      dockerfile: app/webhook/Dockerfile
    volumes:
      - ./app/webhook/data:/app/webhook/data
  bot:
    build:
      context: .
      dockerfile: app/discord-bot/Dockerfile