version: "3"

services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/webhook/data:/app/data
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python /app/discord-bot/bot.py